# config.yml

backend:
  name: git-gateway
  repo: CCLuminy/luminy.org
  branch: jardin # Branch to update (optional; defaults to master)

media_folder: 'assets/images/'
publish_mode: editorial_workflow
site_url: https://jardin.test.luminy.org
display_url: https://jardin.test.luminy.org
custom_logo: /assets/images/authors-logo/logo-jardin.png
locale: fr
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'data'
    label: "Auteurs et Navigations"
    editor:
        preview: false
    files:
      - name: "authors"
        label: "Auteurs"
        file: "_data/authors.yml"
        fields:
          - label: "Auteurs"
            name: "authors"
            widget: "list"
            fields:
              - {                  label: "Nom à afficher", name: "name", widget: string }
              - { required: false, label: "Nom court (pour l'url)", name: "prefix", widget: string }
              - {                  label: "Avatar", name: "avatar", widget: image }
              - { required: false, label: "Image de partage", name: "og_image", widget: string }
              - { required: false, label: "Bannière par défaut", name: "banner", widget: string }
              - {                  label: "Petite description", name: "bio", widget: string }
              - { required: false, label: "Localisation", name: "location", widget: string }
              - { required: false, label: "Email", name: "email", widget: string }
              - { required: false, label: "Site internet", name: "uri", widget: string }
              - { required: false, label: "Facebook", name: "facebook", widget: string }
              - { required: false, label: "Helloasso", name: "helloasso", widget: string }
              - required: false
                label: "Autre"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Label", name: "label", widget: string}
                  - {label: "URL", name: "url", widget: string}
                  - {label: "Icone Fontawesome", name: "icon", widget: string, required: false}

      - name: "navigation"
        label: "Navigations"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation d'entête"
            name: "main"
            widget: "list"
            fields:
              - {label: "Titre", name: "title", widget: string}
              - {label: "Lien", name: "url", widget: string}
          - label: "Navigations par 'auteur'"
            name: "navs"
            widget: "list"
            fields:
              - {label: "Nom court (pour url)", name: "name", widget: string}
              - label: "Sections"
                name: "nav"
                widget: list
                fields:
                  - {label: "Titre", name: "title", widget: string}
                  - {label: "Lien", name: "url", widget: string}
                  - label: "Sous-sections"
                    name: "children"
                    required: false
                    widget: "list"
                    fields:
                      - {label: "Titre", name: "title", widget: string}
                      - {label: "Lien", name: "url", widget: string}

  - name: 'general'
    label: 'Pages générales'
    folder: '_pages/'
    preview_path: '/{{slug}}'
    create: true
    delete: false
    editor:
      preview: true
    fields:
      - {label: "Titre de la page", name: "title", widget: "string"}
      - {label: "Date de dernière mise à jour", name: "last_modified_at", widget: "date"}
      - {label: "Remplacer le bandeau par défaut par un autre ?", name: "overlay_image", widget: "image", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'l-asso'
    label: "l'asso"
    description: "description ici pour la collection lasso"
    folder: '_pages/l-asso'
    preview_path: '/l-asso/{{slug}}'
    create: true
    delete: false
    fields:
      - {label: "Titre de la page", name: "title", widget: "string", description: "description"}
      - {label: "Date de dernière mise à jour", name: "last_modified_at", widget: "date"}
      - {label: "Remplacer le bandeau par défaut par un autre ?", name: "overlay_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'activites'
    label: 'Activités'
    folder: '_pages/activites/'
    preview_path: '/activites/{{slug}}'
    create: true
    delete: false
    fields:
      - {label: "Titre de la page", name: "title", widget: "string"}
      - {label: "Date de dernière mise à jour", name: "last_modified_at", widget: "date"}
      - {label: "Remplacer le bandeau par défaut par un autre ?", name: "overlay_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'grenier'
    label: 'Grenier'
    folder: '_pages/grenier/'
    preview_path: '/grenier/{{slug}}'
    create: true
    delete: false
    fields:
      - {label: "Titre de la page", name: "title", widget: "string"}
      - {label: "Date de dernière mise à jour", name: "last_modified_at", widget: "date"}
      - {label: "Remplacer le bandeau par défaut par un autre ?", name: "overlay_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
